# note: "man 5 sway", under "CRITERIA"
for_window [title = "About Mozilla Firefox"] floating enable
for_window [title = "About Mozilla Thunderbird"] floating enable
for_window [title = "Firefox - Choose User Profile"] floating enable
for_window [title = "Thunderbird - Choose User Profile"] floating enable
for_window [title = "MegaRAC SPX*"] floating enable
for_window [title = "Page Info*"] floating enable
for_window [title = "Source of:*"] floating enable
