# screenshot-full
bindsym Print        exec bash ~/bin/wl-screenshot
bindsym Shift+Print  exec bash ~/bin/wl-screenshot
bindsym $mod+p       exec bash ~/bin/wl-screenshot
bindsym $mod+Shift+p exec bash ~/bin/wl-screenshot

# screenshot-area
bindsym $mod_aux+Print  exec bash ~/bin/wl-screenshot area
bindsym $mod+$mod_aux+p exec bash ~/bin/wl-screenshot area
